GET HTTP://localhost:4000/author HTTP/1.1s

####

POST HTTP://localhost:4000/author/create HTTP/1.1s
Content-Type: application/json

{
    "name": "pippo",
    "lastname": "malefico",
    "email": "p@l.it",
    "password": "rafa23"
}

####
GET HTTP://localhost:4000/author/6519af34626d520a1c12c689

####
GET HTTP://localhost:4000/comments

####

PATCH  HTTP://localhost:4000/author/update/651ad90166f34f518fdeb8b9

{
    "name": "franco",
    "email": "franco@l.it",
    "date": "23-08-1995",
    
}
####
DELETE   HTTP://localhost:4000/author/delete/651ad90166f34f518fdeb8b9

{
    "name": "franco",
    "email": "franco@l.it",
    "date": "23-08-1995",
   
}

####
GET  HTTP://localhost:4000/posts HTTP/1.1s

####
GET  HTTP://localhost:4000/comments/6532aacf798d15956491b59e HTTP/1.1s

####
POST HTTP://localhost:4000/posts/create HTTP/1.1s
Content-Type: application/json

{
    "category": "fantasy",
    "title": "dio fantasy",
    "images": "img",
    "value": 23,
    "author": "652ac62ef98cea70227ef702"
    
}

####
DELETE HTTP://localhost:4000/posts/delete/652a9af28aed0a1076d4a797 HTTP/1.1s

####

GET  HTTP://localhost:4000/comments/posts/6531ad88fd122325078e9ff3
####
POST HTTP://localhost:4000/send-email HTTP/1.1s
Content-Type: application/json

{
    "subject": "email",
    "message": "dio mail",
    
    
}

####
GET  HTTP://localhost:4000/posts/bytitle?title=Evo HTTP/1.1s


####
POST HTTP://localhost:4000/comments/create HTTP/1.1s
Content-Type: application/json

{
    "comment": "articolo de merda w duotone",
    "rate": 1,
    "author": "652ac62ef98cea70227ef702"
}

####
POST HTTP://localhost:4000/login HTTP/1.1s
Content-Type: application/json

{
    
    "email": "p@l.it",
    "password": "rafa"
}